import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-12 py-8 text-lg font-bold text-slate-600 flex justify-center bg-white absolute top-0 right-0 left-0">
          <Link
            className="px-4 py-2 hover:underline underline-offset-4"
            href="/"
          >
            Home
          </Link>
          <Link
            className="px-4 py-2 hover:underline underline-offset-4"
            href="/12"
          >
            Another page
          </Link>
        </nav>
        <main className="bg-slate-100 min-h-dvh">{children}</main>
      </body>
    </html>
  );
}
